# 1. Βρες ένα έτοιμο λειτουργικό με Python 3.9 (ελαφριά έκδοση)
FROM python:3.11-slim

# 2. Φτιάξε έναν φάκελο μέσα στο container που θα λέγεται /app
WORKDIR /app

# 3. Αντέγραψε το requirements.txt και κάνε εγκατάσταση τα πακέτα
COPY requirements.txt .
RUN pip install -r requirements.txt

# 4. Αντέγραψε ΟΛΟ τον κώδικά σου (producer.py, consumer.py, φάκελος pirlib κλπ) μέσα στο container
COPY pirlib/ pirlib/

COPY consumer.py .
COPY producer.py .
